### ISSUE TITLE
Show details, at least one line

### ISSUE THREAD

**Issue by stonecrusher** [collinbarrett/FilterLists#275]
The new design makes it impossible to look through and choose filter lists which I don't know yet because all the important description details (including dependencies or merge notes) are hidden in a popup.

Since design seems to be focused on mobile, why not add another column for desktop?

By the way the old design with
```CSS
button,
input[type="button"],
input[type="reset"],
input[type="submit"],
.button,
.content .widget .textwidget a.button,
.entry-content a.button,
.entry-content a.more-link {
    padding-top: 0 !important;
    padding-bottom: 0 !important; }
```
was way more clear and compact.

I'm not so happy at the moment but filterlists.com is still the most complete summary of filterlists I know.
