### ISSUE TITLE
convert data files from json to yaml

### ISSUE THREAD

**Issue by ghost** [collinbarrett/FilterLists#717]
- [x] Feature Request / Question

It occurred to me that _if_ there is a way to automate the listing process / ease the process for those submitting new or updated info, perhaps a YAML file that receives pull requests each in YAML format which is visually simpler than using JSON format, then _maybe_ it could be a feature to test in a branch designated specifically for a testing period of (n)days until it’s decided to incorporate it, albeit freshly begun, into the master branch or not.

*Example files:*

- **JSON**
````json
{
    "id": 1296,
    "emailAddress": "intr0@intr0.com",
    "description": "DomainVoider is dedicated to providing AdGuard Pro for iOS users with custom built, privacy and security focused filters using a simplified adblocking format.",
    "homeUrl": "https://intr0.com/",
    "issuesUrl": "https://gitlab.com/intr0/DomainVoider/issues",
    "licenseId": 19,
    "name": "DomainVoider",
    "syntaxId": 3,
    "updatedDate": "2019-03-01T14:20:54",
    "viewUrl": "https://gitlab.com/intr0/DomainVoider/raw/master/DomainVoider.txt"
  }
````

- **YAML**
````yaml
id: 1296
emailAddress: intr0@intr0.com
description: 'DomainVoider is dedicated to providing AdGuard Pro for iOS users with custom built, privacy and security focused filters using a simplified adblocking format.'
homeUrl: 'https://intr0.com/'
issuesUrl: 'https://gitlab.com/intr0/DomainVoider/issues'
licenseId: 19
name: DomainVoider
syntaxId: 3
updatedDate: '2019-03-01T14:20:54'
viewUrl: 'https://gitlab.com/intr0/DomainVoider/raw/master/DomainVoider.txt'
````
